### ISSUE TITLE
Release querydsl-contrib 4.0.7

### ISSUE THREAD

**Issue by kevinleturc** [querydsl/querydsl-contrib#14]
Hi,

Is it possible to release the 4.0.6 version, as recent upgrades on spring-data require this version.

Regards

**Comment by timowest** [comment]
3.6.6, 4.0.6 or both?

**Comment by kevinleturc** [comment]
Just 4.0.6, thank you.

**Comment by kevinleturc** [comment]
Hi, do you want me to do changement for the 4.0.6 release ?

**Comment by timowest** [comment]
I can do the release today. sorry for the delay.

**Comment by Shredder121** [comment]
@timowest sorry, but bump?

**Comment by kevinleturc** [comment]
Hello, 
As spring-data uses querydsl 4.0.7 now, is it possible to fix the project for 4.0.7 version ?
Furthemore, as spring follows the minor version of querydsl, I can help you to release the contrib version.
Regards

**Comment by timowest** [comment]
Sorry for the delay, released 4.0.8 now.
